version: "2"
services:
  elasticsearch:
    ports:
      - 9200:9200
  backend:
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - ERROR_WITH_STACK=true
  frontend:
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
