version: "2"
services:
  # Elasticsearch
  elasticsearch:
    image: elasticsearch:${ES_VERSION}
    restart: ${RESTART_POLICY}
    volumes:
      - ${PROJECT_PATH}/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ${PROJECT_PATH}/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ES_JAVA_OPTS
      - TAKE_FILE_OWNERSHIP=1

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: ${RESTART_POLICY}
    depends_on:
      - elasticsearch
    volumes:
      - ${PROJECT_PATH}/backend:/backend
    environment:
      - MODE
      - LOG_CONSOLE_LEVEL
      - LOG_FILE_LEVEL
      - ELASTIC_URL
      - BACKEND_PORT

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: ${RESTART_POLICY}
    depends_on:
      - backend
    ports:
      - ${HOST_HTTP_PORT}:80
    volumes:
      - ${PROJECT_PATH}/docker/frontend/nginx.${MODE}.conf:/etc/nginx/nginx.conf
      - ${PROJECT_PATH}/frontend:/frontend
    environment:
      - MODE
